version: '3.8'

services:
  backend:
    build:
      context: .  # Path to the directory containing the Dockerfile for backend
      dockerfile: backend/Dockerfile  # Path to the Dockerfile for backend
    ports:
      - "5000:5000"  # Expose backend service on port 5000
    networks:
      - my-network

  frontend:
    build:
      context: .  # Path to the directory containing the Dockerfile for frontend
      dockerfile: Dockerfile  # Ensure this is the correct path and name of your frontend Dockerfile
    ports:
      - "5173:5173"  # Expose frontend service on port 5173
    networks:
      - my-network

networks:
  my-network:
    driver: bridge  # Default network driver
